Use Image.LANCZOS instead of Image.ANTIALIAS for thumbnails
SciTools-incubator/image-meta-tag pull request #153
Opened 2024-01-11 10:19 UTC by pdearnshaw

Image.ANTIALIAS was deprecated prior to pillow v9.4, but also removed at v10. Therefore ImageMetaTag will not be able to produce thumbnail images when used in combination with pillow v10 or above. This change applies the suggested fix of using Image.LANCZOS instead.

2024-01-11 10:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SciTools-incubator/image-meta-tag?pullRequest=153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SciTools-incubator/image-meta-tag?pullRequest=153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SciTools-incubator/image-meta-tag?pullRequest=153) it.</sub>

2024-01-11 11:12 UTC, melissaebrooks commented
Thanks Paul - could you do this instead of just switching to the LANCZOS:

        if hasattr(Image, 'LANCZOS'):
            im_thumb.thumbnail(do_thumb, Image.LANCZOS)
        else:
            im_thumb.thumbnail(do_thumb, Image.ANTIALIAS)

2024-01-11 11:22 UTC, melissaebrooks requested changes
Could you do this instead please? This will keep functionality on older environments

    if hasattr(Image, 'LANCZOS'):
        im_thumb.thumbnail(do_thumb, Image.LANCZOS)
    else:
        im_thumb.thumbnail(do_thumb, Image.ANTIALIAS)

2024-01-12 13:32 UTC, pdearnshaw commented
I have updated the branch as requested.

2024-01-23 17:15 UTC, melissaebrooks commented
The test.py script included a logo resize that triggers some additonal code that used ANTIALIAS. Rather than going back to you, I added the same required lines to that function too.

As the code was developed with a test case, and new functionality added to it, it's useful to run:
  python test.py
and: 
  python test.py --minimal

to catch errors.

2024-01-23 17:16 UTC, melissaebrooks approved these changes

2024-01-23 17:18 UTC, merged